- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - [./scripts/installation/gcloud.sh, Installing gcloud]
    - [echo "source ~/.dotfiles/.gcloudalias" >> ~/.zshrc]

- link:
    ~/.dotfiles/.gcloudalias : gcloud/gcloudalias
    ~/.dotfiles/.gcloudalias-base : gcloud/gcloudalias-base

# after installation run: gcloud init to setup gcloud environment (dotbot does not support interactive command)
