- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - [./scripts/installation/kubectl.sh, Installing kubectl]
    - [echo "source ~/.dotfiles/.kubectlalias" >> ~/.zshrc]

- link:
    ~/.dotfiles/.kubectlalias : kubectl/kubectlalias
    ~/.dotfiles/.kubectlalias-base : kubectl/kubectlalias-base

 
# after install kubectl, config need to be setup either via yml file or with gcloud command
