- defaults:
    shell:
        stdin : true
        stdout: true
        sterr : true
        quiet : false
    link:
        create: true
        relink: true
        force: true

- link:
    ~/bin/kubectx : kubectx/kubectx
    ~/bin/kubens : kubectx/kubens

# latest version of kubectx / kubens at the time being is not working with fzf
# changed the directive #!/usr/bin/env bash to #!/usr/bin/env zsh worked (also change set -eou pipefail to set-eo pipefail as zsh does not support -u)