# status: not test neovim installation script on macos yet

- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true
        force: true

- shell:
    - ['[[ "$OSTYPE" == "linux-gnu"* ]] && ./scripts/installation/nvim.sh', Installing neovim on Linux]
    - ['[[ "$OSTYPE" == "darwin"* ]] && ./scripts/installation/nvim-macos.sh', Installing neovim on MacOS]

- link:
    ~/.config/nvim/init.vim       : nvim/init.vim
    ~/.config/nvim/conf           : nvim/conf
    ~/.config/nvim/after/ftplugin : nvim/ftplugin
    ~/.config/nvim/snippets       : nvim/snippets
    ~/.ctags                      : nvim/conf/ctags
    ~/.config/TabNine/tabnine_config.json : nvim/coc/extensions/tabnine_config.json

