- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - [[[ "$OSTYPE" == "linux-gnu"* ]] && ./scripts/installation/vscode.sh, Installing VSCode on Linux]
    - [echo "source ~/.dotfiles/.vscodealias" >> ~/.zshrc]

- link:
    ~/.dotfiles/.vscodealias : vscode/vscodealias
    ~/.dotfiles/.vscodealias-base : vscode/vscodealias-base
