- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - [./scripts/installation/vscode.sh]
    - [echo "source ~/.dotfiles/.vscodealias" >> ~/.zshrc]

- link:
    ~/.dotfiles/.vscodealias : vscode/vscodealias
    ~/.dotfiles/.vscodealias-base : vscode/vscodealias-base
