- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create : true
        relink : true
        force  : true

- clean: ['~', '~/.bash/custom' ,'~/.zsh/custom']

- shell:
    - [./scripts/installation/zsh.sh, Installing zsh & zplug]

- link:
    ~/.zshrc        : zsh/zshrc
    ~/.bash/custom  : scripts/base # load base custom scripts that can be used for both bash and zsh env
    ~/.zsh/custom   : zsh/custom # load zsh custom scripts

