# Load zplug (zsh plugin manager) and neccessary zsh plugins
# Comment this out if would like to use oh-my-zsh or another zsh plugins manager
source ~/.dotfiles/.zshrc-plugins

# Base script - avoid to touch this file to keep source code compatible for further update
source ~/.dotfiles/.zshrc-base

# Customization goes here to override default zshrc configuration

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/longluong/.gcloud/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/longluong/.gcloud/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/longluong/.gcloud/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/longluong/.gcloud/google-cloud-sdk/completion.zsh.inc'; fi
source ~/.dotfiles/.gitalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.kubectlalias
source ~/.dotfiles/.gitalias
source ~/.dotfiles/.npmalias
source ~/.dotfiles/.kubectlalias
