# Load zplug (zsh plugin manager) and neccessary zsh plugins
# Comment this out if would like to use oh-my-zsh or another zsh plugins manager
source ~/.dotfiles/.zshrc-plugins

# Base script - avoid to touch this file to keep source code compatible for further update
source ~/.dotfiles/.zshrc-base

# Make sure locale is UTF8 to avoid fzf error
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Customization goes here to override default zshrc configuration
export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
alias ll="ls -alG"
DISABLE_CORRECTION="true"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/.gcloud/google-cloud-sdk/path.zsh.inc' ]; then . '~/.gcloud/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/.gcloud/google-cloud-sdk/completion.zsh.inc' ]; then . '~/.gcloud/google-cloud-sdk/completion.zsh.inc'; fi
source ~/.dotfiles/.gitalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.kubectlalias
source ~/.dotfiles/.gitalias
source ~/.dotfiles/.npmalias
source ~/.dotfiles/.kubectlalias
source ~/.dotfiles/.vscodealias

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
