# Load zplug (zsh plugin manager) and neccessary zsh plugins
# Comment this out if would like to use oh-my-zsh or another zsh plugins manager
source ~/.dotfiles/.zshrc-plugins

# Base script - avoid to touch this file to keep source code compatible for further update
source ~/.dotfiles/.zshrc-base

# Make sure locale is UTF8 to avoid fzf error
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Customization goes here to override default zshrc configuration
export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
alias ll="ls -alG"
DISABLE_CORRECTION="true"
source ~/.dotfiles/.gitalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.kubectlalias
source ~/.dotfiles/.gitalias
source ~/.dotfiles/.npmalias
source ~/.dotfiles/.kubectlalias
source ~/.dotfiles/.vscodealias

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# pnpm
export PNPM_HOME="/Users/longluong/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.gcloudalias

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/longluong/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/longluong/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/longluong/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/longluong/google-cloud-sdk/completion.zsh.inc'; fi
source ~/.dotfiles/.gitalias
source ~/.dotfiles/.npmalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.kubectlalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.gcloudalias
source ~/.dotfiles/.kubectlalias
source ~/.dotfiles/.npmalias
source ~/.dotfiles/.npmalias
source ~/.dotfiles/.npmalias
source ~/.dotfiles/.vscodealias
source ~/.dotfiles/.npmalias
